# -*- coding: utf-8 -*-
"""Predict the salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sOX1XLWJYGJuLOxpJXZdwPyOUOVu_U1O
"""

import pandas as pd

df = pd.read_csv('w2_position_salaries-220925-153437.csv')

df.head()

X=df['Level']
Y=df['Salary']

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score

linear_model = LinearRegression()
# linear_model.fit(X,Y)
# print(f'R squre = {linear_model.score(Y,X)}')

linear_model.fit(X.values.reshape(-1, 1), Y)  # Reshape X for single feature
linear_r2 = r2_score(Y, linear_model.predict(X.values.reshape(-1, 1)))

print(linear_r2)

for degree in [2, 3, 4]:
    poly_model = PolynomialFeatures(degree=degree)
    X_poly = poly_model.fit_transform(X.values.reshape(-1, 1))
    poly_model = LinearRegression()
    poly_model.fit(X_poly, Y)
    poly_r2 = r2_score(Y, poly_model.predict(X_poly))
    print(f"Polynomial Regression (degree {degree}) R2:", poly_r2)

# 5. Print R2 scores
print("Linear Regression R2:", linear_r2)